# ---
# apiVersion: v1
# kind: Namespace
# metadata:
# name: deployment-system
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
# name: admin-user
# namespace: deployment-system
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
# name: admin-user
# roleRef:
# apiGroup: rbac.authorization.k8s.io
# kind: ClusterRole
# name: cluster-admin
# subjects:
# - kind: ServiceAccount
# name: admin-user
# namespace: deployment-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: deploy
  namespace: deployment-system
spec:
  replicas: 1
  template:
    metadata:
      name: deploy
    spec:
      serviceAccountName: ${CLUSTER_NAME}-user
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: deploy
          image: k8deployment
          imagePullPolicy: Never
          env:
            - name: URL
              value: https://github.com/bdagdeviren/k8s-yaml.git
            - name: TOKEN
              value: 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
            - name: BRANCH
              value: main
      restartPolicy: Never